Algoritmo "mostrar_nome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2023
Var
   // Seção de Declarações das variáveis


Inicio
   escreval("O nome do usuario é Fulano")
   escreval("O nome do usuario é Ciclano")


Fimalgoritmo